name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  pull-requests: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          cache: false # never use caching in release builds

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: pnpm
          registry-url: https://registry.npmjs.org
          package-manager-cache: false  # never use caching in release builds

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browser
        run: pnpm exec playwright install

      - name: Verify releasable packages
        run: pnpm release:check

      - name: Create or update release PR
        id: changesets
        uses: changesets/action@v1 # v2 is next, compatible with v3 CLI, but we're using v2 --> action v1
        with:
          version-script: pnpm version
          create-github-releases: false
          commit-mode: github-api
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to npm with trusted publishing
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: pnpm release
        env:
          NPM_CONFIG_PROVENANCE: 'true'
